const CONFIG = {

  // FORM
  FORM_SHEET_NAME: "Form Responses 1",
    // Spreadsheet Google Form Response
  FORM_SPREADSHEET_ID:"1UCZYpAsxbnkNq4A_u0F2fg--1hRbSrNMqdthrss3rXM",

  // DASHBOARD
  DASHBOARD_SHEET_NAME: "Dashboard",
  LOG_SHEET_NAME: "Logs",

  // PHOTOGRAPHER
  PHOTOGRAPHER_SHEET_NAME: "Form Responses 1",

  // SPREADSHEET IDS
  DASHBOARD_SPREADSHEET_ID: "1sRXKSnc-hZImJF09_95E6TirBr5bQrfZo2UJBznjmOk",
  PHOTOGRAPHER_SPREADSHEET_ID: "1KVi33lJQ3oSMe-vyIeO_ZtDFBnGuqFhW_CGQVgorAhk",

  // GOOGLE CALENDAR
  CALENDAR_ID: "24b6793537bca89df054cc37115c7a522714ec104490b640cdfbb76875cee158@group.calendar.google.com",

  // STATUS
  PAYMENT_DEFAULT: "DP",
  PROJECT_DEFAULT: "Not Assign",

  // DASHBOARD COLUMN INDEX
  COL: {
    TIMESTAMP: 1,
    FORM_ROW_ID: 2,
    CALENDAR_ID_1: 3,
    CALENDAR_ID_2: 4,
    BOOKING_ID: 5,
    CLIENT_NAME: 6,
    UNIVERSITY: 7,
    FACULTY: 8,
    DATE: 9,
    TIME_1: 10,
    TIME_2: 11,
    LOCATION: 12,
    PACKAGE: 13,
    INSTAGRAM: 14,
    WHATSAPP: 15,
    NOTES: 16,
    SUMMARY: 17,
    PHOTOGRAPHER: 18,
    ACTION_CALENDAR: 19,
    PAYMENT_STATUS: 20,
    PROJECT_STATUS: 21,
    DEADLINE: 22,
    LAST_UPDATE: 23,
    SYSTEM_MESSAGE: 24
  }
};